// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/shaileshpandey/jokebyname/models"
)

// ListJokeOKCode is the HTTP code returned for type ListJokeOK
const ListJokeOKCode int = 200

/*ListJokeOK Returns requested Entities.

swagger:response listJokeOK
*/
type ListJokeOK struct {

	/*
	  In: Body
	*/
	Payload *models.IndividualWithJoke `json:"body,omitempty"`
}

// NewListJokeOK creates ListJokeOK with default headers values
func NewListJokeOK() *ListJokeOK {

	return &ListJokeOK{}
}

// WithPayload adds the payload to the list joke o k response
func (o *ListJokeOK) WithPayload(payload *models.IndividualWithJoke) *ListJokeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list joke o k response
func (o *ListJokeOK) SetPayload(payload *models.IndividualWithJoke) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListJokeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
