// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListJokeHandlerFunc turns a function with the right signature into a list joke handler
type ListJokeHandlerFunc func(ListJokeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListJokeHandlerFunc) Handle(params ListJokeParams) middleware.Responder {
	return fn(params)
}

// ListJokeHandler interface for that can handle valid list joke params
type ListJokeHandler interface {
	Handle(ListJokeParams) middleware.Responder
}

// NewListJoke creates a new http.Handler for the list joke operation
func NewListJoke(ctx *middleware.Context, handler ListJokeHandler) *ListJoke {
	return &ListJoke{Context: ctx, Handler: handler}
}

/*ListJoke swagger:route GET / listJoke

Display joke for random person

Returns joke for individual person.

*/
type ListJoke struct {
	Context *middleware.Context
	Handler ListJokeHandler
}

func (o *ListJoke) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListJokeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
