// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Individual Joke Teller API
Tell's joke for individual


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
