// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// JokeDetail joke detail
// swagger:model JokeDetail
type JokeDetail struct {

	// category
	Category []string `json:"category"`

	// id
	ID int64 `json:"id,omitempty"`

	// joke
	Joke string `json:"joke,omitempty"`
}

// Validate validates this joke detail
func (m *JokeDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JokeDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JokeDetail) UnmarshalBinary(b []byte) error {
	var res JokeDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
